//Array of objects containing DDV recipes
//Appetizers
let appetizers = [
    {
        "name": "Arendellian Pickled Herring",
        "ingredientOne" : "Herring",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Onion",
        "ingredientFour" : "Garlic",
        "ingredientFive" : "Any spice",
        "stars" : 5,
        "sellPrice" : 556, 
        "energy": 2102
    },
    {
        "name": "Bell Pepper Puffs",
        "ingredientOne" : "Bell Pepper",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 606, 
        "energy": 1272
    },
    {
        "name": "Buñuelos",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Cheese",
        "ingredientThree" : "Milk",
        "ingredientFour" : "Egg",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 948, 
        "energy": 1881
    },
    {
        "name": "Cheese Platter",
        "ingredientOne" : "Cheese",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 216, 
        "energy": 482
    },
    {
        "name": "Chili Pepper Puffs",
        "ingredientOne" : "Chili Pepper",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Milk",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 669, 
        "energy": 1382
    },
    {
        "name": "Coffee",
        "ingredientOne" : "Coffee Bean",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 43, 
        "energy": 730
    },
    {
        "name": "Crackers",
        "ingredientOne" : "Any grain",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 2, 
        "energy": 80
    },
    {
        "name": "Creamy Soup",
        "ingredientOne" : "Any spice",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Potato",
        "ingredientFour" : "Any vegetable",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 576, 
        "energy": 1138
    },
    {
        "name": "Crudités",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 26, 
        "energy": 83
    },
    {
        "name": "Dream Fizz",
        "ingredientOne" : "Dreamlight Fruit",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Wheat",
        "ingredientFour" : "Slush Ice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 316, 
        "energy": 1550
    },
    {
        "name": "Eggplant Puffs",
        "ingredientOne" : "Eggplant",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 991, 
        "energy": 1941
    },
    {
        "name": "French Fries",
        "ingredientOne" : "Canola",
        "ingredientTwo" : "Potato",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 304, 
        "energy": 342
    },
    {
        "name": "Gazpacho",
        "ingredientOne" : "Cucumber",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Onion",
        "ingredientFour" : "Any spice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 556, 
        "energy": 821
    },
    {
        "name": "Green Salad",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Lettuce",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 20, 
        "energy": 180
    },
    {
        "name": "Grilled Vegetables",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 9, 
        "energy": 83
    },
    {
        "name": "Grilled Veggie Platter",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 33, 
        "energy": 161
    },
    {
        "name": "Hard-Boiled Eggs",
        "ingredientOne" : "Egg",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 264, 
        "energy": 578
    },
    {
        "name": "Large Seafood Platter",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Any seafood",
        "ingredientThree" : "Any seafood",
        "ingredientFour" : "Any seafood",
        "ingredientFive" : "Lemon",
        "stars" : 5,
        "sellPrice" : 56, 
        "energy": 1810
    },
    {
        "name": "Latte",
        "ingredientOne" : "Coffee Bean",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 345, 
        "energy": 1358
    },
    {
        "name": "Marinated Herring",
        "ingredientOne" : "Herring",
        "ingredientTwo" : "Onion",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 305, 
        "energy": 723
    },
    {
        "name": "Mocha",
        "ingredientOne" : "Coffee Bean",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Cocoa Bean",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 425, 
        "energy": 2246
    },
    {
        "name": "Okra Soup",
        "ingredientOne" : "Okra",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 136, 
        "energy": 99
    },
    {
        "name": "Onion Puffs",
        "ingredientOne" : "Onion",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 798, 
        "energy": 1392
    },
    {
        "name": "Oyster Platter",
        "ingredientOne" : "Oyster",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 367, 
        "energy": 1155
    },
    {
        "name": "Peppermint Tea",
        "ingredientOne" : "Lemon",
        "ingredientTwo" : "Mint",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 146, 
        "energy": 993
    },
    {
        "name": "Pickled Herring",
        "ingredientOne" : "Herring",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Onion",
        "ingredientFour" : "Any spice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 431, 
        "energy": 1742
    },
    {
        "name": "Potato Leek Soup",
        "ingredientOne" : "Leek",
        "ingredientTwo" : "Potato",
        "ingredientThree" : "Milk",
        "ingredientFour" : "Onion",
        "ingredientFive" : "Garlic",
        "stars" : 5,
        "sellPrice" : 1400, 
        "energy": 1984
    },
    {
        "name": "Potato Puffs",
        "ingredientOne" : "Potato",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 736, 
        "energy": 1333
    },
    {
        "name": "Pottage",
        "ingredientOne" : "Potato",
        "ingredientTwo" : "Any spice",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 215, 
        "energy": 461
    },
    {
        "name": "Pumpkin Puffs",
        "ingredientOne" : "Pumpkin",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 1400, 
        "energy": 1466
    },
    {
        "name": "Pumpkin Soup",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Ginger",
        "ingredientFour" : "Pumpkin",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 1500, 
        "energy": 1431
    },
    {
        "name": "Purée",
        "ingredientOne" : "Potato",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 151, 
        "energy": 230
    },
    {
        "name": "Roasted Asparagus",
        "ingredientOne" : "Asparagus",
        "ingredientTwo" : "Canola",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 313, 
        "energy": 221
    },
    {
        "name": "Salad",
        "ingredientOne" : "Lettuce",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 9, 
        "energy": 139
    },
    {
        "name": "Sautéed Mushrooms",
        "ingredientOne" : "Mushroom",
        "ingredientTwo" : "Butter",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 286, 
        "energy": 712
    },
    {
        "name": "Seafood Appetizer",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 1, 
        "energy": 242
    },
    {
        "name": "Seafood Platter",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Any seafood",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 2, 
        "energy": 458
    },
    {
        "name": "Soufflé",
        "ingredientOne" : "Cheese",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Milk",
        "ingredientFour" : "Butter",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 1200, 
        "energy": 2386
    },
    {
        "name": "Tomato Soup",
        "ingredientOne" : "Tomato",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 26, 
        "energy": 83
    },
    {
        "name": "Vegetable Soup",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 20, 
        "energy": 120
    },
    {
        "name": "Zucchini Puffs",
        "ingredientOne" : "Zucchini",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 632, 
        "energy": 1216
    }
]

//Entrées 
let entrees = [
    {
        "name": "Apple-Cider-Glazed Salmon",
        "ingredientOne" : "Salmon",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Apple",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 271, 
        "energy": 1572
    },
    {
        "name": "Baked Carp",
        "ingredientOne" : "Carp",
        "ingredientTwo" : "Butter",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 767, 
        "energy": 1894
    },
    {
        "name": "Basil Omelet",
        "ingredientOne" : "Basil",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "Milk",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 982, 
        "energy": 2035
    },
    {
        "name": "Bouillabaisse",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Any seafood",
        "ingredientThree" : "Shrimp",
        "ingredientFour" : "Tomato",
        "ingredientFive" : "Any vegetable",
        "stars" : 5,
        "sellPrice" : 529, 
        "energy": 2114
    },
    {
        "name": "Carp Salad",
        "ingredientOne" : "Carp",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Lettuce",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 617, 
        "energy": 2310
    },
    {
        "name": "Cheesy Crispy Baked Cod",
        "ingredientOne" : "Cod",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 303, 
        "energy": 840
    },
    {
        "name": "Chowder",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Potato",
        "ingredientFour" : "Any vegetable",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 547, 
        "energy": 1186
    },
    {
        "name": "Creamy Garlic Scallops",
        "ingredientOne" : "Scallop",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Butter",
        "ingredientFour" : "Garlic",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 499, 
        "energy": 1844
    },
    {
        "name": "Crispy Baked Cod",
        "ingredientOne" : "Cod",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 47, 
        "energy": 337
    },
    {
        "name": "Fish Creole",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Garlic",
        "ingredientFour" : "Rice",
        "ingredientFive" : "Tomato",
        "stars" : 5,
        "sellPrice" : 241, 
        "energy": 822
    },
    {
        "name": "Fish 'n' Chips",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Canola",
        "ingredientFour" : "Potato",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 356, 
        "energy": 697
    },
    {
        "name": "Fish Pasta",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Garlic",
        "ingredientThree" : "Wheat",
        "ingredientFour" : "Milk",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 439, 
        "energy": 1282
    },
    {
        "name": "Fish Pie",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 269, 
        "energy": 867
    },
    {
        "name": "Fish Risotto",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Rice",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 352, 
        "energy": 939
    },
    {
        "name": "Fish Salad",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Lettuce",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 58, 
        "energy": 1140
    },
    {
        "name": "Fish Sandwiches",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 3, 
        "energy": 337
    },
    {
        "name": "Fish Soup",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Milk",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 334, 
        "energy": 978
    },
    {
        "name": "Fish Steak",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Basil",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 66, 
        "energy": 537
    },
    {
        "name": "Fish Tacos",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Corn",
        "ingredientThree" : "Chili Pepper",
        "ingredientFour" : "Cheese",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 412, 
        "energy": 1171
    },
    {
        "name": "Fugu Sushi",
        "ingredientOne" : "Fugu",
        "ingredientTwo" : "Rice",
        "ingredientThree" : "Seaweed",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 1300, 
        "energy": 3261
    },
    {
        "name": "Ghostly Fish Steak",
        "ingredientOne" : "Here and There Fish",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Asparagus",
        "ingredientFour" : "Bell Pepper",
        "ingredientFive" : "Oregano",
        "stars" : 5,
        "sellPrice" : 3500, 
        "energy": 3282
    },
    {
        "name": "Greek Pizza",
        "ingredientOne" : "Any Spice",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Onion",
        "ingredientFour" : "Cheese",
        "ingredientFive" : "Wheat",
        "stars" : 5,
        "sellPrice" : 630, 
        "energy": 1152
    },
    {
        "name": "Grilled Fish",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 1, 
        "energy": 290
    },
    {
        "name": "Grilled Fish Entree",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 11, 
        "energy": 340
    },
    {
        "name": "Gumbo",
        "ingredientOne" : "Okra",
        "ingredientTwo" : "Shrimp",
        "ingredientThree" : "Chili Pepper",
        "ingredientFour" : "Tomato",
        "ingredientFive" : "Onion",
        "stars" : 5,
        "sellPrice" : 1000, 
        "energy": 2226
    },
    {
        "name": "Hearty Salad",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Lettuce",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 33, 
        "energy": 224
    },
    {
        "name": "Hors d'Oeuvres",
        "ingredientOne" : "Any spice",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 24, 
        "energy": 202
    },
    {
        "name": "Kappa Maki",
        "ingredientOne" : "Seaweed",
        "ingredientTwo" : "Cucumber",
        "ingredientThree" : "Rice",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 335, 
        "energy": 462
    },
    {
        "name": "Kronk's Spinach Puffs",
        "ingredientOne" : "Spinach",
        "ingredientTwo" : "Cheese",
        "ingredientThree" : "Canola",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 461, 
        "energy": 750
    },
    {
        "name": "Lancetfish Paella",
        "ingredientOne" : "Lancetfish",
        "ingredientTwo" : "Shrimp",
        "ingredientThree" : "Any seafood",
        "ingredientFour" : "Tomato",
        "ingredientFive" : "Rice",
        "stars" : 5,
        "sellPrice" : 1600, 
        "energy": 4550
    },
    {
        "name": "Leek Soup",
        "ingredientOne" : "Leek",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 370, 
        "energy": 414
    },
    {
        "name": "Lemon Garlic Swordfish",
        "ingredientOne" : "Swordfish",
        "ingredientTwo" : "Garlic",
        "ingredientThree" : "Lemon",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 1100, 
        "energy": 3713
    },
    {
        "name": "Lioness Feast",
        "ingredientOne" : "Mushroom",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Oregano",
        "ingredientFour" : "Here and There Fish",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 3100, 
        "energy": 2368
    },
    {
        "name": "Lobster Roll",
        "ingredientOne" : "Lobster",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Lemon",
        "ingredientFour" : "Butter",
        "ingredientFive" : "Garlic",
        "stars" : 5,
        "sellPrice" : 1900, 
        "energy": 4928
    },
    {
        "name": "Maguro Sushi",
        "ingredientOne" : "Tuna",
        "ingredientTwo" : "Seaweed",
        "ingredientThree" : "Rice",
        "ingredientFour" : "Ginger",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 413, 
        "energy": 1206
    },
    {
        "name": "Maki",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Seaweed",
        "ingredientThree" : "Rice",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 114, 
        "energy": 471
    },
    {
        "name": "Margherita Pizza",
        "ingredientOne" : "Any spice",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "Wheat",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 336, 
        "energy": 818
    },
    {
        "name": "Marvelous Jam",
        "ingredientOne" : "Dreamlight Fruit",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 54, 
        "energy": 932
    },
    {
        "name": "Mediterranean Salad",
        "ingredientOne" : "Cucumber",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Onion",
        "ingredientFour" : "Lettuce",
        "ingredientFive" : "Any spice",
        "stars" : 5,
        "sellPrice" : 605, 
        "energy": 976
    },
    {
        "name": "Mushroom Pizza",
        "ingredientOne" : "Mushroom",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Tomato",
        "ingredientFour" : "Cheese",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 351, 
        "energy": 837
    },
    {
        "name": "Mushu's Congee",
        "ingredientOne" : "Rice",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Mushroom",
        "ingredientFour" : "Garlic",
        "ingredientFive" : "Ginger",
        "stars" : 5,
        "sellPrice" : 753, 
        "energy": 1658
    },
    {
        "name": "Omelet",
        "ingredientOne" : "Egg",
        "ingredientTwo" : "Cheese",
        "ingredientThree" : "Milk",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 882, 
        "energy": 1751
    },
    {
        "name": "Pan-Fried Angler Fish",
        "ingredientOne" : "Anglerfish",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Zucchini",
        "ingredientFour" : "Potato",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 2500, 
        "energy": 4194
    },
    {
        "name": "Pan-Seared Bass & Vegetables",
        "ingredientOne" : "Bass",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 57, 
        "energy": 394
    },
    {
        "name": "Pan-Seared Tilapia & Vegetables",
        "ingredientOne" : "Tilapia",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 862, 
        "energy": 2194
    },
    {
        "name": "Pasta",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 30, 
        "energy": 117
    },
    {
        "name": "Peanut Butter Sandwich",
        "ingredientOne" : "Peanut",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 262, 
        "energy": 592
    },
    {
        "name": "Pizza",
        "ingredientOne" : "Tomato",
        "ingredientTwo" : "Cheese",
        "ingredientThree" : "Wheat",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 284, 
        "energy": 607
    },
    {
        "name": "Poached Basil-Butter Sturgeon",
        "ingredientOne" : "White Sturgeon",
        "ingredientTwo" : "Basil",
        "ingredientThree" : "Lemon",
        "ingredientFour" : "Butter",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 2200, 
        "energy": 4961
    },
    {
        "name": "Porridge",
        "ingredientOne" : "Milk",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 301, 
        "energy": 668
    },
    {
        "name": "Porridge with Fruits",
        "ingredientOne" : "Milk",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Any fruit",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 353, 
        "energy": 1155
    },
    {
        "name": "Ranch Salad",
        "ingredientOne" : "Lettuce",
        "ingredientTwo" : "Bell Pepper",
        "ingredientThree" : "Corn",
        "ingredientFour" : "Tomato",
        "ingredientFive" : "Onion",
        "stars" : 5,
        "sellPrice" : 396, 
        "energy": 714
    },
    {
        "name": "Ratatouille",
        "ingredientOne" : "Tomato",
        "ingredientTwo" : "Eggplant",
        "ingredientThree" : "Zucchini",
        "ingredientFour" : "Onion",
        "ingredientFive" : "Any spice",
        "stars" : 5,
        "sellPrice" : 914, 
        "energy": 1572
    },
    {
        "name": "Sake Maki",
        "ingredientOne" : "Rice",
        "ingredientTwo" : "Seaweed",
        "ingredientThree" : "Salmon",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 323, 
        "energy": 1101
    },
    {
        "name": "Sake Sushi",
        "ingredientOne" : "Salmon",
        "ingredientTwo" : "Rice",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 274, 
        "energy": 1000
    },
    {
        "name": "Savory Fish",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 43, 
        "energy": 985
    },
    {
        "name": "Scrambled Egg",
        "ingredientOne" : "Egg",
        "ingredientTwo" : "Cheese",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 520, 
        "energy": 1070
    },
    {
        "name": "Seafood Pasta",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Milk",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 325, 
        "energy": 921
    },
    {
        "name": "Seafood Pie",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 269, 
        "energy": 813
    },
    {
        "name": "Seafood Salad",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Lettuce",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 11, 
        "energy": 349
    },
    {
        "name": "Seafood Soup",
        "ingredientOne" : "Any seafood",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 23, 
        "energy": 340
    },
    {
        "name": "Seared Rainbow Trout",
        "ingredientOne" : "Rainbow Trout",
        "ingredientTwo" : "Tomato",
        "ingredientThree" : "Onion",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 338, 
        "energy": 889
    },
    {
        "name": "Simple Fried Perch",
        "ingredientOne" : "Perch",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 380, 
        "energy": 1317
    },
    {
        "name": "Smoked Peanuts and Anglerfish",
        "ingredientOne" : "Anglerfish",
        "ingredientTwo" : "Peanut",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 2200, 
        "energy": 3960
    },
    {
        "name": "Sole Meunière",
        "ingredientOne" : "Sole",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "Lemon",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 637, 
        "energy": 2337
    },
    {
        "name": "Spaghetti Arrabbiata",
        "ingredientOne" : "Tomato",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Chili Pepper",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 141, 
        "energy": 373
    },
    {
        "name": "Spicy Baked Bream",
        "ingredientOne" : "Bream",
        "ingredientTwo" : "Chili Pepper",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 767, 
        "energy": 2075
    },
    {
        "name": "Steamed Fugu",
        "ingredientOne" : "Fugu",
        "ingredientTwo" : "Ginger",
        "ingredientThree" : "Garlic",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 1400, 
        "energy": 3668
    },
    {
        "name": "Sushi",
        "ingredientOne" : "Any fish",
        "ingredientTwo" : "Rice",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 80, 
        "energy": 405
    },
    {
        "name": "Sweet & Sour Kingfish Steak",
        "ingredientOne" : "Kingfish",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Lemon",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 702, 
        "energy": 2292
    },
    {
        "name": "Sweet Udon",
        "ingredientOne" : "Dreamlight Fruit",
        "ingredientTwo" : "Rice",
        "ingredientThree" : "Any seafood",
        "ingredientFour" : "Any sweet",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 180, 
        "energy": 1427
    },
    {
        "name": "Tamagoyaki",
        "ingredientOne" : "Egg",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 310, 
        "energy": 689
    },
    {
        "name": "Tasty Salad",
        "ingredientOne" : "Lettuce",
        "ingredientTwo" : "Cucumber",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "Any spice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 292, 
        "energy": 650
    },
    {
        "name": "Tasty Veggies",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Any spice",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 36, 
        "energy": 246
    },
    {
        "name": "Tekka Maki",
        "ingredientOne" : "Tuna",
        "ingredientTwo" : "Soya",
        "ingredientThree" : "Seaweed",
        "ingredientFour" : "Rice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 366, 
        "energy": 984
    },
    {
        "name": "Teriyaki Salmon",
        "ingredientOne" : "Soya",
        "ingredientTwo" : "Salmon",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Rice",
        "ingredientFive" : "Ginger",
        "stars" : 5,
        "sellPrice" : 637, 
        "energy": 1726
    },
    {
        "name": "Tuna Burger",
        "ingredientOne" : "Tuna",
        "ingredientTwo" : "Onion",
        "ingredientThree" : "Lemon",
        "ingredientFour" : "Wheat",
        "ingredientFive" : "Any vegetable",
        "stars" : 5,
        "sellPrice" : 491, 
        "energy": 1922
    },
    {
        "name": "Vegetarian Pizza",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Tomato",
        "ingredientFour" : "Cheese",
        "ingredientFive" : "Wheat",
        "stars" : 5,
        "sellPrice" : 350, 
        "energy": 754
    },
    {
        "name": "Vegetarian Stew",
        "ingredientOne" : "Potato",
        "ingredientTwo" : "Carrot",
        "ingredientThree" : "Onion",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 475, 
        "energy": 617
    },
    {
        "name": "Vegetarian Taco",
        "ingredientOne" : "Corn",
        "ingredientTwo" : "Chili Pepper",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "Any vegetable",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 423, 
        "energy": 925
    },
    {
        "name": "Veggie Casserole",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Any vegetable",
        "ingredientThree" : "Cheese",
        "ingredientFour" : "Any spice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 324, 
        "energy": 821
    },
    {
        "name": "Veggie Pasta",
        "ingredientOne" : "Tomato",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Any vegetable",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 43, 
        "energy": 158
    },
    {
        "name": "Veggie Pasta",
        "ingredientOne" : "Any vegetable",
        "ingredientTwo" : "Butter",
        "ingredientThree" : "Wheat",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 279, 
        "energy": 634
    },
    {
        "name": "Veggie Skewers",
        "ingredientOne" : "Mushroom",
        "ingredientTwo" : "Zucchini",
        "ingredientThree" : "Onion",
        "ingredientFour" : "Bell Pepper",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 427, 
        "energy": 767
    },
    {
        "name": "Walleye en Papillote",
        "ingredientOne" : "Walleye",
        "ingredientTwo" : "Basil",
        "ingredientThree" : "Oregano",
        "ingredientFour" : "Any vegetable",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 1700, 
        "energy": 3689
    },
]

//Desserts
let desserts = [
    {
        "name": "'My Hero' Cookie",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Butter",
        "ingredientThree" : "Any sweet",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 294, 
        "energy": 679
    },
    {
        "name": "Apple Pie",
        "ingredientOne" : "Apple",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 303, 
        "energy": 1137
    },
    {
        "name": "Apple Sorbet",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Apple",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 271, 
        "energy": 1077
    },
    {
        "name": "Aurora's Cake",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Any fruit",
        "ingredientFive" : "Milk",
        "stars" : 5,
        "sellPrice" : 786, 
        "energy": 2030
    },
    {
        "name": "Banana Ice Cream",
        "ingredientOne" : "Ice Slush",
        "ingredientTwo" : "Banana",
        "ingredientThree" : "Milk",
        "ingredientFour" : "Sugarcane",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 641, 
        "energy": 1884
    },
    {
        "name": "Banana Pie",
        "ingredientOne" : "Banana",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 308, 
        "energy": 1227
    },
    {
        "name": "Banana Split",
        "ingredientOne" : "Ice Slush",
        "ingredientTwo" : "Banana",
        "ingredientThree" : "Milk",
        "ingredientFour" : "Sugarcane",
        "ingredientFive" : "Any sweet",
        "stars" : 5,
        "sellPrice" : 714, 
        "energy": 2074
    },
    {
        "name": "Beignets",
        "ingredientOne" : "Canola",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Sugarcane",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 524, 
        "energy": 912
    },
    {
        "name": "Berry Salad",
        "ingredientOne" : "Raspberry",
        "ingredientTwo" : "Blueberry",
        "ingredientThree" : "Gooseberry",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 139, 
        "energy": 2210
    },
    {
        "name": "Birthday Cake",
        "ingredientOne" : "Cocoa Bean",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Egg",
        "ingredientFive" : "Butter",
        "stars" : 5,
        "sellPrice" : 749, 
        "energy": 2310
    },
    {
        "name": "Biscuits",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 294, 
        "energy": 679
    },
    {
        "name": "Blueberry Pie",
        "ingredientOne" : "Blueberry",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 308, 
        "energy": 1227
    },
    {
        "name": "Boba Tea",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 323, 
        "energy": 714
    },
    {
        "name": "Candy",
        "ingredientOne" : "Any sweet",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 22, 
        "energy": 123
    },
    {
        "name": "Caramel Apples",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Apple",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 56, 
        "energy": 638
    },
    {
        "name": "Carrot Cake",
        "ingredientOne" : "Carrot",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Sugarcane",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 427, 
        "energy": 908
    },
    {
        "name": "Cheesecake",
        "ingredientOne" : "Cheese",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Any fruit",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 332, 
        "energy": 1161
    },
    {
        "name": "Cherry Pie",
        "ingredientOne" : "Cherry",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 326, 
        "energy": 1497
    },
    {
        "name": "Chocolate Chip Cookies",
        "ingredientOne" : "Cocoa Bean",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Butter",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 373, 
        "energy": 1569
    },
    {
        "name": "Chocolate Ice Cream",
        "ingredientOne" : "Cocoa Bean",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Milk ",
        "ingredientFour" : "Slush Ice",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 655, 
        "energy": 2074
    },
    {
        "name": "Chocolate Waffles",
        "ingredientOne" : "Cocoa Bean",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Milk",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 735, 
        "energy": 2223
    },
    {
        "name": "Coconut Boba Tea",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Coconut",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 406, 
        "energy": 1653
    },
    {
        "name": "Coconut Cake",
        "ingredientOne" : "Coconut",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Sugarcane",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 424, 
        "energy": 1750
    },
    {
        "name": "Coconut Ice Cream",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Coconut",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 661, 
        "energy": 2169
    },
    {
        "name": "Crepe",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Egg",
        "ingredientThree" : "Milk",
        "ingredientFour" : "Vanilla",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 768, 
        "energy": 1624
    },
    {
        "name": "Dream Ice Cream",
        "ingredientOne" : "Dreamlight Fruit",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Slush Ice",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 588, 
        "energy": 1976
    },
    {
        "name": "Fruit Salad",
        "ingredientOne" : "Any fruit",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 25, 
        "energy": 450
    },
    {
        "name": "Fruit Sorbet",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Any fruit",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 222, 
        "energy": 857
    },
    {
        "name": "Fruitcake",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Any fruit",
        "ingredientThree" : "Any fruit",
        "ingredientFour" : "Any fruit",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 96, 
        "energy": 1511
    },
    {
        "name": "Gingerbread House",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Ginger",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Vanilla",
        "ingredientFive" : "Egg",
        "stars" : 5,
        "sellPrice" : 641, 
        "energy": 1460
    },
    {
        "name": "Gooseberry Boba Tea",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Gooseberry",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 418, 
        "energy": 1833
    },
    {
        "name": "Gray Stuff",
        "ingredientOne" : "Any dairy",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Cocoa Bean",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 114, 
        "energy": 1046
    },
    {
        "name": "Hot Cocoa",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Cocoa",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 401, 
        "energy": 1563
    },
    {
        "name": "Ice Cream",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 558, 
        "energy": 1158
    },
    {
        "name": "Jam Waffles",
        "ingredientOne" : "Any fruit",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Milk",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 709, 
        "energy": 1843
    },
    {
        "name": "Lemon Sorbet",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 237, 
        "energy": 1112
    },
    {
        "name": "Meringue Pie",
        "ingredientOne" : "Lemon",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Butter",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 667, 
        "energy": 2014
    },
    {
        "name": "Minnie's Gingerbread Cookies",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Ginger",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 132, 
        "energy": 379
    },
    {
        "name": "Mint Boba Tea",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Mint",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 460, 
        "energy": 1032
    },
    {
        "name": "Mint Candy",
        "ingredientOne" : "Mint",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 128, 
        "energy": 391
    },
    {
        "name": "Mint Chocolate",
        "ingredientOne" : "Mint",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Butter",
        "ingredientFour" : "Cocoa",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 490, 
        "energy": 1827
    },
    {
        "name": "Mint Sorbet",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Mint",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 299, 
        "energy": 695
    },
    {
        "name": "Pastry Cream and Fruits",
        "ingredientOne" : "Any fruit",
        "ingredientTwo" : "Any fruit",
        "ingredientThree" : "Any fruit",
        "ingredientFour" : "Milk",
        "ingredientFive" : "Sugarcane",
        "stars" : 5,
        "sellPrice" : 497, 
        "energy": 2332
    },
    {
        "name": "Pawpsicle",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Any fruit",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 265, 
        "energy": 987
    },
    {
        "name": "Peanut Butter Waffles",
        "ingredientOne" : "Peanut",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Milk",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 978, 
        "energy": 1938
    },
    {
        "name": "Plain Snow Cones",
        "ingredientOne" : "Any ice",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 180, 
        "energy": 410
    },
    {
        "name": "Raspberry Boba Tea",
        "ingredientOne" : "Sugarcane",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Raspberry",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 377, 
        "energy": 1203
    },
    {
        "name": "Red Fruit Pie",
        "ingredientOne" : "Any fruit",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 297, 
        "energy": 1047
    },
    {
        "name": "Red Fruit Sorbet",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Raspberry",
        "ingredientThree" : "Gooseberry",
        "ingredientFour" : "Sugarcane",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 359, 
        "energy": 2179
    },
    {
        "name": "Root Beer",
        "ingredientOne" : "Ginger",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Vanilla",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 250, 
        "energy": 690
    },
    {
        "name": "Shake",
        "ingredientOne" : "Any dairy",
        "ingredientTwo" : "",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 1,
        "sellPrice" : 30, 
        "energy": 142
    },
    {
        "name": "Snow White's Gooseberry Pie",
        "ingredientOne" : "Gooseberry",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 338, 
        "energy": 1677
    },
    {
        "name": "Sour Snow Cones",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Lemon",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 282, 
        "energy": 1257
    },
    {
        "name": "Spring Chocolate",
        "ingredientOne" : "Spring V-EGG-etable",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Cocoa Bean",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 254, 
        "energy": 1392
    },
    {
        "name": "Spring Egg Bowl",
        "ingredientOne" : "Egg-cellent Fruit",
        "ingredientTwo" : "Spring V-EGG-etable",
        "ingredientThree" : "Wild Spring Egg",
        "ingredientFour" : "Cocoa Bean",
        "ingredientFive" : "Sugarcane",
        "stars" : 5,
        "sellPrice" : 370, 
        "energy": 1942
    },

    {
        "name": "Spring Mimosa Eggs",
        "ingredientOne" : "Spring V-EGG-etable",
        "ingredientTwo" : "Wild Spring Egg",
        "ingredientThree" : "Egg-cellent Fruit",
        "ingredientFour" : "Basil",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 298, 
        "energy": 1095
    },
    {
        "name": "Sweet Slush",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Any sweet",
        "ingredientThree" : "",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 2,
        "sellPrice" : 219, 
        "energy": 510
    },
    {
        "name": "Tropical Pop",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Any fruit",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Coconut",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 347, 
        "energy": 1989
    },
    {
        "name": "Vanilla Ice Cream",
        "ingredientOne" : "Slush Ice",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Sugarcane",
        "ingredientFour" : "Vanilla",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 688, 
        "energy": 1475
    },
    {
        "name": "Waffles",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Milk",
        "ingredientThree" : "Egg",
        "ingredientFour" : "Any sweet",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 706, 
        "energy": 1455
    },
    {
        "name": "Wedding Cake",
        "ingredientOne" : "Butter",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Vanilla",
        "ingredientFour" : "Egg",
        "ingredientFive" : "Wheat",
        "stars" : 5,
        "sellPrice" : 785, 
        "energy": 1680
    },
    {
        "name": "Whimsical Pie",
        "ingredientOne" : "Dreamlight Fruit",
        "ingredientTwo" : "Wheat",
        "ingredientThree" : "Butter",
        "ingredientFour" : "",
        "ingredientFive" : "",
        "stars" : 3,
        "sellPrice" : 324, 
        "energy": 1497
    },
    {
        "name": "Wonderland Cookies",
        "ingredientOne" : "Butter",
        "ingredientTwo" : "Sugarcane",
        "ingredientThree" : "Vanilla",
        "ingredientFour" : "Wheat",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 406, 
        "energy": 970
    },
    {
        "name": "Yule Log",
        "ingredientOne" : "Wheat",
        "ingredientTwo" : "Cocoa Bean",
        "ingredientThree" : "Vanilla",
        "ingredientFour" : "Cherry",
        "ingredientFive" : "",
        "stars" : 4,
        "sellPrice" : 213, 
        "energy": 2147
    }
]

//Special cases:
///Crudités (not all veggies)
///Grilled Vegetables (not all veggies)
///Sushi (not salmon)
///Red Fruit Pie (not all fruits)
//Shake (not egg or cheese)
